oryx:
  leanrepo:
    settings:
      groupId: 913d77d0-c3e7-4faa-bb36-165a2040a70c
      schemaName: category
      schema: |
        {
          "$id": "https://oryx-gateway.net/schemas/Category",
          "$schema": "http://json-schema.org/draft-07/schema#",
          "title": "Category",
          "type": "object",
          "description": "A collection of Product Offerings, intended for a specific DistributionChannel, enhanced with additional information such as SLA parameters, invoicing and shipping details",
          "required": ["@type"],
          "properties": {
            "id": {
              "type": "string",
              "description": "Unique identifier of the category"
            },
            "href": {
              "type": "string",
              "description": "Reference of the category"
            },
            "description": {
              "type": "string",
              "description": "Description of the category"
            },
            "isRoot": {
              "type": "boolean",
              "description": "If true, this Boolean indicates that the category is a root of categories"
            },
            "lastUpdate": {
              "type": "string",
              "format": "date-time",
              "description": "Date and time of the last update"
            },
            "lifecycleStatus": {
              "type": "string",
              "description": "Used to indicate the current lifecycle status"
            },
            "name": {
              "type": "string",
              "description": "Name of the category"
            },
            "parentId": {
              "type": "string",
              "description": "Unique identifier of the parent category"
            },
            "version": {
              "type": "string",
              "description": "Category version"
            },
            "productOffering": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ProductOfferingRef"
              },
              "description": "A product offering represents entities that are orderable from the provider of the catalog, this resource includes pricing information."
            },
            "subCategory": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/CategoryRef"
              },
              "description": "The category resource is used to group product offerings, service and resource candidates in logical containers. Categories can contain other (sub-)categories and/or product offerings."
            },
            "validFor": {
              "$ref": "#/definitions/TimePeriod",
              "description": "The period for which the category is valid"
            },
            "@baseType": {
              "type": "string",
              "description": "When sub-classing, this defines the super-class"
            },
            "@schemaLocation": {
              "type": "string",
              "format": "uri",
              "description": "A URI to a JSON-Schema file that defines additional attributes and relationships"
            },
            "@type": {
              "type": "string",
              "description": "When sub-classing, this defines the sub-class Extensible name"
            }
          },
          "definitions": {
            "ProductOfferingRef": {
              "type": "object",
              "description": "ProductOffering reference. A product offering represents entities that are orderable from the provider of the catalog, this resource includes pricing information.",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "unique identifier"
                },
                "href": {
                  "type": "string",
                  "format": "uri",
                  "description": "Hyperlink reference"
                },
                "name": {
                  "type": "string",
                  "description": "Name of the related entity."
                },
                "@baseType": {
                  "type": "string",
                  "description": "When sub-classing, this defines the super-class"
                },
                "@schemaLocation": {
                  "type": "string",
                  "format": "uri",
                  "description": "A URI to a JSON-Schema file that defines additional attributes and relationships"
                },
                "@type": {
                  "type": "string",
                  "description": "When sub-classing, this defines the sub-class Extensible name"
                },
                "@referredType": {
                  "type": "string",
                  "description": "The actual type of the target instance when needed for disambiguation."
                }
              },
              "required": ["id"]
            },
            "CategoryRef": {
              "type": "object",
              "description": "The category for grouping recommendations",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "unique identifier"
                },
                "href": {
                  "type": "string",
                  "format": "uri",
                  "description": "Hyperlink reference"
                },
                "name": {
                  "type": "string",
                  "description": "Name of the related entity."
                },
                "version": {
                  "type": "string",
                  "description": "Category version"
                },
                "@baseType": {
                  "type": "string",
                  "description": "When sub-classing, this defines the super-class"
                },
                "@schemaLocation": {
                  "type": "string",
                  "format": "uri",
                  "description": "A URI to a JSON-Schema file that defines additional attributes and relationships"
                },
                "@type": {
                  "type": "string",
                  "description": "When sub-classing, this defines the sub-class Extensible name"
                },
                "@referredType": {
                  "type": "string",
                  "description": "The actual type of the target instance when needed for disambiguation."
                }
              },
              "required": ["id"]
            },
            "TimePeriod": {
              "type": "object",
              "description": "A period of time, either as a deadline (endDateTime only) a startDateTime only, or both",
              "properties": {
                "endDateTime": {
                  "example": "1985-04-12T23:20:50.52Z",
                  "type": "string",
                  "format": "date-time",
                  "description": "End of the time period, using IETC-RFC-3339 format"
                },
                "startDateTime": {
                  "example": "1985-04-12T23:20:50.52Z",
                  "type": "string",
                  "format": "date-time",
                  "description": "Start of the time period, using IETC-RFC-3339 format"
                }
              }
            }
          }
        }
