oryx:
  leanrepo:
    settings:
      groupId: 76deea5e-39b5-4ee5-8f18-a6d37c1fb6db
      schemaName: geographicsite
      schema: |
        {
          "$id": "https://example.com/schemas/GeographicSite",
          "$schema": "http://json-schema.org/draft-07/schema#",
          "title": "GeographicSite",
          "description": "Defines a Site as a convenience class that allows to easily refer to places important to other entities, where a geographic place is the entity that can answer the question \u201cwhere?\u201d, allowing to determine where things are in relation to the earth's surface, and can be represented either in a textual structured way (geographic address) or as a geometry referred to a spatial reference system (geographic location)",
          "type": "object",
          "required": ["@type"],
          "properties": {
            "id": {
              "description": "unique identifier (UUID)",
              "type": "string",
              "format": "uuid",
              "readOnly": true,
              "example": "c73bcdcc-2669-4bf6-81d3-e4ae73fb11fd"
            },
            "href": {
              "description": "Hyperlink reference",
              "type": "string",
              "readOnly": true,
              "format": "uri"
            },
            "code": {
              "type": "string",
              "description": "A code that may be used for some addressing schemes eg: [ANSI T1.253-1999]"
            },
            "description": {
              "type": "string",
              "description": "Text describing additional information regarding the site"
            },
            "name": {
              "type": "string",
              "description": "A user-friendly name for the place, such as [Paris Store], [London Store], [Main Home]"
            },
            "status": {
              "type": "string",
              "description": "The condition of the GeographicSite, such as planned, underConstruction, cancelled, active, inactive, former"
            },
            "calendar": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/CalendarPeriod"
              }
            },
            "place": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/PlaceRefOrValue"
              }
            },
            "relatedParty": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/RelatedParty"
              }
            },
            "siteRelationship": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/GeographicSiteRelationship"
              }
            },
            "@baseType": {
              "type": "string",
              "description": "When sub-classing, this defines the super-class"
            },
            "@schemaLocation": {
              "type": "string",
              "format": "uri",
              "description": "A URI to a JSON-Schema file that defines additional attributes and relationships"
            },
            "@type": {
              "type": "string",
              "description": "When sub-classing, this defines the sub-class entity name"
            }
          },
          "definitions": {
            "CalendarPeriod": {
              "type": "object",
              "required": ["@type"],
              "properties": {
                "day": {
                  "type": "string",
                  "description": "Day where the calendar status applies (e.g.: monday, mon-to-fri, weekdays, weekend, all week, ...)"
                },
                "status": {
                  "type": "string",
                  "description": "Indication of the availability of the site (e.g.: open)"
                },
                "timeZone": {
                  "type": "string",
                  "description": "Indication of the timezone applicable to the calendar information (e.g.: Paris, GMT+1)"
                },
                "hourPeriod": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/HourPeriod"
                  }
                },
                "@baseType": {
                  "type": "string",
                  "description": "When sub-classing, this defines the super-class"
                },
                "@schemaLocation": {
                  "type": "string",
                  "format": "uri",
                  "description": "A URI to a JSON-Schema file that defines additional attributes and relationships"
                },
                "@type": {
                  "type": "string",
                  "description": "When sub-classing, this defines the sub-class entity name"
                }
              }
            },
            "PlaceRefOrValue": {
              "type": "object",
              "description": "A  place described by reference or by value linked to a specific entity. The polymorphic attributes @type, @schemaLocation & @referredType are related to the place entity and not the PlaceRefOrValue class itself",
              "required": ["@type"],
              "properties": {
                "id": {
                  "description": "unique identifier (UUID)",
                  "type": "string",
                  "format": "uuid",
                  "readOnly": true,
                  "example": "c73bcdcc-2669-4bf6-81d3-e4ae73fb11fd"
                },
                "href": {
                  "description": "Hyperlink reference",
                  "type": "string",
                  "readOnly": true,
                  "format": "uri"
                },
                "name": {
                  "type": "string",
                  "description": "A user-friendly name for the place, such as [Paris Store], [London Store], [Main Home]"
                },
                "@referredType": {
                  "type": "string",
                  "description": "The actual type of the target instance when needed for disambiguation."
                },
                "@baseType": {
                  "type": "string",
                  "description": "When sub-classing, this defines the super-class"
                },
                "@schemaLocation": {
                  "type": "string",
                  "format": "uri",
                  "description": "A URI to a JSON-Schema file that defines additional attributes and relationships"
                },
                "@type": {
                  "type": "string",
                  "description": "When sub-classing, this defines the sub-class entity name"
                }
              }
            },
            "RelatedParty": {
              "type": "object",
              "description": "Related Entity reference. A related party defines party or party role linked to a specific entity.",
              "required": ["@referredType", "@type"],
              "properties": {
                "id": {
                  "description": "unique identifier (UUID)",
                  "type": "string",
                  "format": "uuid",
                  "readOnly": true,
                  "example": "c73bcdcc-2669-4bf6-81d3-e4ae73fb11fd"
                },
                "href": {
                  "description": "Hyperlink reference",
                  "type": "string",
                  "readOnly": true,
                  "format": "uri"
                },
                "name": {
                  "type": "string",
                  "description": "Name of the related entity."
                },
                "role": {
                  "type": "string",
                  "description": "Role played by the related party"
                },
                "@referredType": {
                  "type": "string",
                  "description": "The actual type of the target instance when needed for disambiguation."
                },
                "@baseType": {
                  "type": "string",
                  "description": "When sub-classing, this defines the super-class"
                },
                "@schemaLocation": {
                  "type": "string",
                  "format": "uri",
                  "description": "A URI to a JSON-Schema file that defines additional attributes and relationships"
                },
                "@type": {
                  "type": "string",
                  "description": "When sub-classing, this defines the sub-class entity name"
                }
              }
            },
            "GeographicSiteRelationship": {
              "required": ["relationshipType", "@type"],
              "type": "object",
              "properties": {
                "id": {
                  "description": "unique identifier (UUID)",
                  "type": "string",
                  "format": "uuid",
                  "readOnly": true,
                  "example": "c73bcdcc-2669-4bf6-81d3-e4ae73fb11fd"
                },
                "href": {
                  "description": "Hyperlink reference",
                  "type": "string",
                  "readOnly": true,
                  "format": "uri"
                },
                "relationshipType": {
                  "type": "string",
                  "description": "Type of relationship"
                },
                "role": {
                  "type": "string",
                  "description": "Role of the related site in the relationship"
                },
                "validFor": {
                  "$ref": "#/definitions/TimePeriod",
                  "description": "Validity for the relationship"
                },
                "@baseType": {
                  "type": "string",
                  "description": "When sub-classing, this defines the super-class"
                },
                "@schemaLocation": {
                  "type": "string",
                  "format": "uri",
                  "description": "A URI to a JSON-Schema file that defines additional attributes and relationships"
                },
                "@type": {
                  "type": "string",
                  "description": "When sub-classing, this defines the sub-class entity name"
                }
              }
            },
            "TimePeriod": {
              "type": "object",
              "description": "A period of time, either as a deadline (endDateTime only) a startDateTime only, or both",
              "properties": {
                "endDateTime": {
                  "type": "string",
                  "format": "date-time",
                  "description": "End of the time period, using IETC-RFC-3339 format"
                },
                "startDateTime": {
                  "type": "string",
                  "format": "date-time",
                  "description": "Start of the time period, using IETC-RFC-3339 format. If you define a start, you must also define an end"
                }
              }
            },
            "HourPeriod": {
              "type": "object",
              "required": ["@type"],
              "properties": {
                "endHour": {
                  "type": "string",
                  "description": "The time when the status ends applying"
                },
                "startHour": {
                  "type": "string",
                  "description": "The time when the status starts applying"
                },
                "@baseType": {
                  "type": "string",
                  "description": "When sub-classing, this defines the super-class"
                },
                "@schemaLocation": {
                  "type": "string",
                  "format": "uri",
                  "description": "A URI to a JSON-Schema file that defines additional attributes and relationships"
                },
                "@type": {
                  "type": "string",
                  "description": "When sub-classing, this defines the sub-class entity name"
                }
              }
            }
          }
        }
