tags:
  mongodb: true

global:
  imagePullPolicy: "IfNotPresent"
  imagePullSecrets: []
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

oda:
  enabled: true

ingress:
  host: "oryx.itrative.com"
  enabled: true

oryx:
  settings:
    gateway: 
      configMap: "oryx-gateway"
    mongodb:
      url: "mongodb://root:pa55w0rd@leanrepo-mongodb-svc:27017/?authSource=admin"
  leanrepoInit:
    image: oryxgateway/leanrepo-init:3.1.0
  leanrepo:
    image: oryxgateway/leanrepo:3.1.0
