global:
  imagePullPolicy: "IfNotPresent"
  imagePullSecrets: []
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

oda:
  enabled: false

ingress:
  host: "oryx.itrative.com"
  enabled: false

dependencies:
  broker: 
    strimzi: true
  schemaregistry:
    apicurio: true
  flink: true

apicurio-registry:
  registry:
    enabled: true
    kafka:
      bootstrapServers: oryx-kafka-kafka-bootstrap:9092

kafka-ui:
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: broker
          bootstrapServers: oryx-kafka:9092
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false

oryx:
  settings:
    schemaRegistry:
      vendor: "apicurio"
      env: 
        SCHEMA_REGISTRY_URL: "http://oryx-apicurio-registry:8080/apis/registry/v2/"
    decorator: "none"
    namingStrategy: "suffixed_name"
    topics:
      topic: "TMF688.topic.notification"
      hub: "TMF688.hub.notification"
    flink:
      url: "http://oryx-flink-rest:8081"
    brokerProperties: |
      bootstrap.servers=http://oryx-kafka-kafka-bootstrap:9092
    imagePullSecrets:
      - "gateway-registry"
  gatewayInit: 
    image: oryxgateway/gateway-init:3.1.0-devel
  gateway:
    image: oryxgateway/gateway:3.1.0-devel
  operator: {}