apiVersion: v2
name: oryx-gateway
version: 3.0.0
kubeVersion: ">= 1.19.0"
type: application
appVersion: "3.0.0"
description: A Helm chart for Oryx Gateway

dependencies:
  - name: kafka
    version: "26.3.1"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: dependencies.broker.kafka
  - name: kafka-ui
    version: "0.7.5"
    repository: "https://provectus.github.io/kafka-ui-charts"
    condition: dependencies.broker.kafka
  - name: cp-helm-charts
    version: "0.6.1"
    repository: "https://confluentinc.github.io/cp-helm-charts/"
    condition: dependencies.schemaregistry.confluent
  - name: apicurio-registry
    version: "3.0.1"
    repository: "oci://ghcr.io/eshepelyuk/helm"
    condition: dependencies.schemaregistry.apicurio
  - name: flink-kubernetes-operator
    version: "1.7.0"
    repository: https://downloads.apache.org/flink/flink-kubernetes-operator-1.7.0/
    condition: dependencies.flink
