apiVersion: v2
name: oryx-gateway
version: 3.0.0
kubeVersion: ">= 1.19.0-0"
type: application
appVersion: "3.0.0"
description: A Helm chart for Oryx Gateway

dependencies:
  - name: confluent-for-kubernetes
    version: "0.921.2"
    repository: "https://packages.confluent.io/helm"
    condition: dependencies.broker.confluent,dependencies.schemaregistry.confluent
  - name: strimzi-kafka-operator
    version: "0.40.0"
    repository: "oci://quay.io/strimzi-helm"
    condition: dependencies.broker.strimzi
  - name: flink-kubernetes-operator
    version: "1.8.0"
    repository: https://downloads.apache.org/flink/flink-kubernetes-operator-1.8.0/
    condition: dependencies.flink
  - name: apicurio-registry
    version: "3.8.0"
    repository: "oci://ghcr.io/eshepelyuk/helm"
    condition: dependencies.schemaregistry.apicurio
  - name: kafka-ui
    version: "0.7.5"
    repository: "https://provectus.github.io/kafka-ui-charts"
    condition: dependencies.broker.strimzi,dependencies.broker.confluent
