apiVersion: v2
name: oryx-gateway
version: 1.2.0
kubeVersion: ">= 1.19.0"
type: application
appVersion: "2.6.0"
description: A Helm chart for Oryx Gateway

dependencies:
  - name: mongodb-sharded
    version: "6.3.2"
    repository: "https://charts.bitnami.com/bitnami"
