apiVersion: v2
name: oryx-leanrepo
version: 3.0.0
kubeVersion: ">= 1.19.0-0"
type: application
appVersion: "3.0.0"
description: A Helm chart for Oryx Gateway
dependencies:
  - name: community-operator
    version: "0.9.0"
    repository: "https://mongodb.github.io/helm-charts"
    tags:
      - mongodb
