global:
  imagePullPolicy: "IfNotPresent"
  imagePullSecrets: []
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

oda:
  enabled: true

ingress: 
  enabled: true

dependencies:
  mongodb: true

oryx:
  settings:
    gateway: 
      configMap: "gateway-gateway"
    mongodb:
      url: "mongodb://root:pa55w0rd@leanrepo-mongodb-sharded:27017"
      database: "db"
    imagePullSecrets:
      - "gateway-registry"
  leanrepoInit:
    name: "leanrepo-init"
    image: oryxgateway/leanrepo-init:3.0.0
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 4Gi
  leanrepo:
    enabled: true
    type: leanrepo
    name: leanrepo
    image: oryxgateway/leanrepo:3.0.0
    replicas: 1
    updateStrategy: "RollingUpdate"
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}  
    components: []

mongodb-sharded:
  auth:
    enabled: true
    rootUser: root
    rootPassword: pa55w0rd
  shards: 3
  configsvr:
    replicaCount: 3
    resources:
      requests:
        memory: 256Mi
        cpu: 200m
      limits:
        memory: 512Mi
        cpu: 500m
  mongos:
    replicaCount: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 1000m
  shardsvr:
    dataNode:
      replicaCount: 2
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 1000m
