tags:
  mongodb: false

global:
  imagePullPolicy: "IfNotPresent"
  imagePullSecrets: []
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

oda:
  enabled: false

ingress: 
  host: ""
  enabled: false

oryx:
  settings:
    gateway: 
      configMap: "gateway-gateway"
    mongodb:
      username: root
      password: pa55w0rd
      database: db
      url: ""
      replicas: 3
    imagePullSecrets:
      - "gateway-registry"
  leanrepoInit:
    name: "leanrepo-init"
    image: oryxgateway/leanrepo-init:3.0.0
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 4Gi
  leanrepo:
    enabled: true
    type: leanrepo
    name: leanrepo
    image: oryxgateway/leanrepo:3.0.0
    replicas: 1
    updateStrategy: "RollingUpdate"
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}  
    components: []

community-operator: 
  community-operator-crds:
    enabled: false
