{{- if .Values.dependencies.flink }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}-flink-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}-flink
  labels:
    app: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
spec:
  rules:
    - host: flink.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-gateway-flink-rest
                port:
                  number: 8081
---
{{- end }}
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}-flink
spec:
  image: flink:1.18-java17
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "4"
    state.savepoints.dir: file:///flink-data/savepoints
    state.checkpoints.dir: file:///flink-data/checkpoints
    high-availability.type: kubernetes
    high-availability.storageDir: file:///flink-data/restore
    restart-strategy.type: fixed-delay
    restart-strategy.fixed-delay.attempts: "1048576"
    restart-strategy.fixed-delay.delay: "15s"
    rest.client.max-content-length: "524288000"
    rest.server.max-content-length: "524288000"
    env.java.opts.all: "--add-opens=java.base/java.util=ALL-UNNAMED
      --add-opens=java.base/java.lang=ALL-UNNAMED
      --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
      --add-opens=java.base/java.io=ALL-UNNAMED"
  serviceAccount: flink
  mode: native
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      containers:
        - name: flink-main-container
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}
          volumeMounts:
            - name: flink-data
              mountPath: /flink-data
            - name: configs
              mountPath: /opt/oryxgateway/config
      volumes:
        - name: flink-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}-flink-pvc
        - name: configs
          configMap:
            name: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}-files
  jobManager:
    replicas: 1
    resource:
      memory: 1g
      cpu: 1
  taskManager:
    replicas: 3
    resource:
      memory: 2g
      cpu: 1
{{- end }}