oryx:
  gateway:
    replicas: 1

kafka:
  broker:
    replicaCount: 1
    extraConfig: |
      auto.create.topics.enable: false
      offsets.topic.replication.factor: 1

  zookeeper:
    replicaCount: 1
