{{- if .Values.tags.mongodb }}
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
    tls:
      enabled: false  
  users:
    - name: {{ .Values.oryx.settings.mongodb.username }}
      db: admin
      passwordSecretRef:
        name: {{ .Release.Name }}-mongodb
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdmin
          db:  {{ .Values.oryx.settings.mongodb.database }}
        - name: readWrite
          db:  {{ .Values.oryx.settings.mongodb.database }}
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          initContainers:
            - command:
                - chown
                - -R
                - "2000"
                - /data
              image: busybox
              volumeMounts:
              - mountPath: /data
                name: data-volume
              securityContext:
                runAsNonRoot: false
                runAsUser: 0
                runAsGroup: 0
              name: change-dir-permissions
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: 1000m
                  memory: 1Gi
                requests:
                  cpu: 500m
                  memory: 200Mi
              securityContext:
                runAsNonRoot: false
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
            - name: mongodb-agent
              resources:
                limits:
                  cpu: 1000m
                  memory: 1Gi
                requests:
                  cpu: 500m
                  memory: 200Mi
              securityContext:
                runAsNonRoot: false
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 8G
      - metadata:
          name: logs-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 8G
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb
type: Opaque
stringData:
  password: {{ .Values.oryx.settings.mongodb.password }}
{{- end }}
