{{- if .Values.tags.mongodb }}
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ .Values.oryx.settings.mongodb.username }}
      db: admin
      passwordSecretRef:
        name: {{ .Release.Name }}-mongodb
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdmin
          db:  {{ .Values.oryx.settings.mongodb.database }}
        - name: readWrite
          db:  {{ .Values.oryx.settings.mongodb.database }}
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb
type: Opaque
stringData:
  password: {{ .Values.oryx.settings.mongodb.password }}
{{- end }}
