{{- if .Values.oda.enabled }}
apiVersion: oda.tmforum.org/v1beta1
kind: Component
metadata:
  name: {{ .Release.Name }}-{{ .Values.oryx.leanrepo.type }}
  labels:
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.leanrepo.type }}
spec:
  type: {{ .Values.oryx.leanrepo.type }}
  version: "0.0.1"
  description: "Lean Repository API ODA-Component"
  maintainers:
    - name: Stanislav Oaserele
      email: soaserele@gmail.com
  owners:
    - name: Stanislav Oaserele
      email: soaserele@gmail.com
  coreFunction:
    exposedAPIs:
{{- $releaseName := .Release.Name -}}
{{- range .Values.oryx.leanrepo.components }}
      - name: {{ $releaseName }}-{{ .name }}
        apitype: openapi
        specification: ""
        implementation: {{ .name }}
        path: /{{ .path }}/tmf-api/
        port: 8080
{{- end }}  
    dependentAPIs: [ ]
  eventNotification:
    publishedEvents: [ ] 
    subscribedEvents: [ ]
  management: 
    exposedAPIs: []
    dependentAPIs: []
  security:
    exposedAPIs: 
      - name: partyrole
        apitype: openapi
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
        developerUI: /{{ .Release.Name }}-{{ .Values.oryx.leanrepo.type }}/tmf-api/swagger-ui/index.html
        implementation: {{ .Release.Name }}-{{ .Values.oryx.leanrepo.name }}
        path: /{{ .Release.Name }}-{{ .Values.oryx.leanrepo.type }}/tmf-api/partyRoleManagement/v4
        port: 8080
    dependentAPIs: []
    controllerRole: Admin
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
{{- end }}
