{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.oryx.leanrepo.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.oryx.leanrepo.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.leanrepo.type }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
{{- $releaseName := .Release.Name -}}
{{- $instanceName := .Values.oryx.leanrepo.name -}}
{{- range .Values.oryx.leanrepo.components }}
          - path: /{{ .path }}/
            pathType: Prefix
            backend:
              service:
                name: {{ $releaseName }}-{{ $instanceName }}
                port:
                  number: 8080
{{- end }}  
{{- end }}