{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.redis.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.redis.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.leanrepo.type }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.redis.name }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.redis.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.redis.name }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.leanrepo.type }}
      {{- if or .Values.global.podAnnotations .Values.redis.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.global.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- range $key, $value := .Values.redis.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    spec:
      affinity:
      {{- if or .Values.global.affinity .Values.redis.affinity }}
      {{- if .Values.redis.affinity }}
{{ toYaml .Values.redis.affinity | indent 8 }}
      {{- else }}
{{ toYaml .Values.global.affinity | indent 8 }}
      {{- end }}
      {{- else }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - {{ .Release.Name }}-{{ .Values.redis.name }}
                topologyKey: "kubernetes.io/hostname"
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-{{ .Values.redis.name }}
          image: {{ .Values.redis.image }}
          imagePullPolicy: {{ or .Values.redis.imagePullPolicy .Values.global.imagePullPolicy }}
          args: ["--appendonly", "yes", "--save", "60", "1"]
          ports:
            - containerPort: 6379
              name: redis
          resources:
{{ toYaml .Values.redis.resources | indent 12 }}
          volumeMounts:
            - name: redis-volume
              mountPath: /data
      volumes:
        - name: redis-volume
      {{ if not .Values.redis.persistence.enabled }}
          emptyDir: { }
      {{- else }}
          persistentVolumeClaim:
            claimName: redis-volume-pvc
      {{- end }}

      {{- if .Values.redis.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.redis.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.redis.tolerations }}
      tolerations:
{{ toYaml .Values.redis.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
{{- end }}
