{{- if .Values.ingress.enabled }}
{{- if or .Values.dependencies.broker.strimzi .Values.dependencies.broker.confluent }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-kafka-ui
  labels:
    app: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  rules:
    - host: kafka.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-kafka-ui
                port:
                  number: 80
{{- end }}
{{- end }}