{{- if .Values.dependencies.broker.confluent }}
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: {{ .Release.Name }}-zookeeper
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  podTemplate:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: {{ .Release.Name }}-kafka
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  dataVolumeCapacity: 10Gi
  configOverrides:
    server:
      - delete.topic.enasble=true
      - min.insync.replicas=2
      - num.partitions=3
  podTemplate:
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m
  listeners:
    internal: {}
    external: {}
  dependencies:
    zookeeper:
      endpoint: {{ .Release.Name }}-zookeeper.{{ .Release.Namespace }}.svc.cluster.local:2181
{{- end }}
