apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
data:
  SOME_SECRET_HERE: {{ "s3cr3t" | b64enc | quote}}
