apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
data:
  SCHEMA_REGISTRY_VENDOR: {{ .Values.oryx.settings.schemaRegistry.vendor }}
{{- if .Values.oryx.settings.schemaRegistry }}
{{- range $key, $value := .Values.oryx.settings.schemaRegistry.env }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
  VALUE_DECORATOR: {{ .Values.oryx.settings.decorator }}
  TOPIC_NAMING_STRATEGY: {{ .Values.oryx.settings.namingStrategy }}
  TOPICS_TOPIC: {{ .Values.oryx.settings.topics.topic }}
  HUBS_TOPIC: {{ .Values.oryx.settings.topics.hub }}
  FLINK_URL: {{ .Values.oryx.settings.flink.url }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}-files
  labels:
    app: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
data:
  "broker.properties": |
{{ .Values.oryx.settings.brokerProperties | indent 4 }}
