{{- if .Values.kafka.schemaregistry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.kafka.schemaregistry.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.kafka.schemaregistry.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
spec:
  ports:
    - port: 8081
      name: schemaregistry
  selector:
    app: {{ .Release.Name }}-{{ .Values.kafka.schemaregistry.name }}
    release: {{ .Release.Name }}
{{- end }}
