{{- if .Values.kafka.ksqldb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.kafka.ksqldb.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.kafka.ksqldb.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.kafka.ksqldb.name }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.kafka.ksqldb.replicas }}
  strategy:
    type: {{ .Values.kafka.ksqldb.updateStrategy | default "RollingUpdate" }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.kafka.ksqldb.name }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
      {{- if or .Values.global.podAnnotations .Values.kafka.ksqldb.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.global.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- range $key, $value := .Values.kafka.ksqldb.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    spec:
      affinity:
      {{- if or .Values.global.affinity .Values.kafka.ksqldb.affinity }}
      {{- if .Values.kafka.ksqldb.affinity }}
{{ toYaml .Values.kafka.ksqldb.affinity | indent 8 }}
      {{- else }}
{{ toYaml .Values.global.affinity | indent 8 }}
      {{- end }}
      {{- else }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - {{ .Release.Name }}-{{ .Values.kafka.ksqldb.name }}
                topologyKey: "kubernetes.io/hostname"
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-{{ .Values.kafka.ksqldb.name }}
          image: {{ .Values.kafka.ksqldb.image }}
          imagePullPolicy: {{ or .Values.kafka.ksqldb.imagePullPolicy .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8088
              name: ksqldb
          resources:
{{ toYaml .Values.kafka.ksqldb.resources | indent 12 }}
          env:
            - name: KSQL_LISTENERS
              value: http://0.0.0.0:8088
            - name: KSQL_BOOTSTRAP_SERVERS
              value: {{ .Release.Name }}-{{ .Values.kafka.broker.name }}-headless:9092
            - name: KSQL_KSQL_SERVICE_ID
              value: {{ .Release.Name }}-{{ .Values.kafka.ksqldb.name }}
            - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
              value: http://{{ .Release.Name }}-{{ .Values.kafka.schemaregistry.name }}:8081
            - name: KSQL_HEAP_OPTS
              value: {{ .Values.kafka.ksqldb.settings.heapOptions }}
            {{- range $key, $value := .Values.kafka.ksqldb.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      {{- if .Values.kafka.ksqldb.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.kafka.ksqldb.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.kafka.ksqldb.tolerations }}
      tolerations:
{{ toYaml .Values.kafka.ksqldb.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
{{- end }}
