{{- if .Values.kafka.schemaregistry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.kafka.schemaregistry.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.kafka.schemaregistry.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.kafka.schemaregistry.name }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.kafka.schemaregistry.replicas }}
  strategy:
    type: {{ .Values.kafka.schemaregistry.updateStrategy | default "RollingUpdate" }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.kafka.schemaregistry.name }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
      {{- if or .Values.global.podAnnotations .Values.kafka.schemaregistry.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.global.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- range $key, $value := .Values.kafka.schemaregistry.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    spec:
      affinity:
      {{- if or .Values.global.affinity .Values.kafka.schemaregistry.affinity }}
      {{- if .Values.kafka.schemaregistry.affinity }}
{{ toYaml .Values.kafka.schemaregistry.affinity | indent 8 }}
      {{- else }}
{{ toYaml .Values.global.affinity | indent 8 }}
      {{- end }}
      {{- else }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - {{ .Release.Name }}-{{ .Values.kafka.schemaregistry.name }}
                topologyKey: "kubernetes.io/hostname"
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-{{ .Values.kafka.schemaregistry.name }}
          image: {{ .Values.kafka.schemaregistry.image }}
          imagePullPolicy: {{ or .Values.kafka.schemaregistry.imagePullPolicy .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8081
              name: schemaregistry
          resources:
{{ toYaml .Values.kafka.schemaregistry.resources | indent 12 }}
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
            - name: SCHEMA_REGISTRY_MASTER_ELIGIBILITY
              value: "true"
            - name: SCHEMA_REGISTRY_HEAP_OPTS
              value: {{ .Values.kafka.schemaregistry.settings.heapOptions }}
            - name: SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID
              value: {{ .Release.Name }}-{{ .Values.kafka.schemaregistry.name }}
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://{{ .Release.Name }}-{{ .Values.kafka.broker.name }}-headless:9092
            {{- range $key, $value := .Values.kafka.schemaregistry.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      {{- if .Values.kafka.schemaregistry.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.kafka.schemaregistry.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.kafka.schemaregistry.tolerations }}
      tolerations:
{{ toYaml .Values.kafka.schemaregistry.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
{{- end }}
