{{- if .Values.kafka.broker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.kafka.broker.name }}-headless
  labels:
    app: {{ .Release.Name }}-{{ .Values.kafka.broker.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
spec:
  ports:
    - port: 9092
      name: broker
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-{{ .Values.kafka.broker.name }}
    release: {{ .Release.Name }}
{{- end }}
