{{- if .Values.kafka.broker.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Values.kafka.broker.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.kafka.broker.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
spec:
  serviceName: {{ .Release.Name }}-{{ .Values.kafka.broker.name }}-headless
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.kafka.broker.name }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.kafka.broker.replicas }}
  updateStrategy:
    type: {{ .Values.kafka.broker.updateStrategy | default "RollingUpdate" }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.kafka.broker.name }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
      {{- if or .Values.global.podAnnotations .Values.kafka.broker.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.global.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- range $key, $value := .Values.kafka.broker.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    spec:
      affinity:
      {{- if or .Values.global.affinity .Values.kafka.broker.affinity }}
      {{- if .Values.kafka.broker.affinity }}
{{ toYaml .Values.kafka.broker.affinity | indent 8 }}
      {{- else }}
{{ toYaml .Values.global.affinity | indent 8 }}
      {{- end }}
      {{- else }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - {{ .Release.Name }}-{{ .Values.kafka.broker.name }}
                topologyKey: "kubernetes.io/hostname"
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-{{ .Values.kafka.broker.name }}
          image: {{ .Values.kafka.broker.image }}
          imagePullPolicy: {{ or .Values.kafka.broker.imagePullPolicy .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 9092
              name: kafka
          resources:
{{ toYaml .Values.kafka.broker.resources | indent 12 }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAFKA_HEAP_OPTS
              value: {{ .Values.kafka.broker.settings.heapOptions }}
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{ .Release.Name }}-{{ .Values.kafka.zookeeper.name }}:2181
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
            {{- if .Values.kafka.broker.persistence.enabled }}
            - name: KAFKA_LOG_DIRS
              value: {{ range $k, $e := until (.Values.kafka.broker.persistence.disksPerBroker|int) -}}{{- if $k}}{{- printf ","}}{{end}}{{- printf "/opt/kafka/data-%d/logs" $k -}}{{- end -}}
            {{- else }}
            - name: KAFKA_LOG_DIRS
              value: /opt/kafka/data-0/logs
            {{- end }}
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "false"
            {{- range $key, $value := .Values.kafka.broker.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          command:
            - sh
            - -exc
            - |
              export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
              export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_NAME}.{{ .Release.Name }}-{{ .Values.kafka.broker.name }}-headless:9092 && \
              exec /etc/confluent/docker/run
          {{- if .Values.kafka.broker.persistence.enabled }}
          volumeMounts:
          {{- $disksPerBroker := .Values.kafka.broker.persistence.disksPerBroker | int }}
          {{- range $k, $e := until $disksPerBroker }}
            - name: datadir-{{$k}}
              mountPath: /opt/kafka/data-{{$k}}
          {{- end }}
          {{- else }}
            - name: datadir-0
              mountPath: /opt/kafka/data-0
          {{- end }}
      {{- if not .Values.kafka.broker.persistence.enabled }}
      volumes:
        - name: datadir-0
          emptyDir: { }
      {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      {{- if .Values.kafka.broker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.kafka.broker.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.kafka.broker.tolerations }}
      tolerations:
{{ toYaml .Values.kafka.broker.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
  {{- if .Values.kafka.broker.persistence.enabled }}
  volumeClaimTemplates:
  {{- $disksPerBroker := .Values.kafka.broker.persistence.disksPerBroker | int }}
  {{- $root := . }}
  {{- range $k, $e := until $disksPerBroker }}
    - metadata:
        name: datadir-{{$k}}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $root.Values.kafka.broker.persistence.size }}
        storageClassName: {{ $root.Values.kafka.broker.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
