{{- if .Values.kafka.zookeeper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.kafka.zookeeper.name }}-headless
  labels:
    app: {{ .Release.Name }}-{{ .Values.kafka.zookeeper.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-{{ .Values.kafka.zookeeper.name }}
    release: {{ .Release.Name }}
{{- end }}
