{{- if .Values.oryx.gateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}-secrets
  labels:
    app: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
type: Opaque
data:
  SERVICE_API_KEY: {{ (randAlphaNum 32) | b64enc | quote }}
{{- end }}
