{{- if .Values.dependencies.broker.kafka }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apicurio-ui-ingress
  labels:
    app: {{ .Release.Name }}-{{ .Values.oryx.gateway.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  rules:
    - host: apicurio.oryx.itrative.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-apicurio-registry
                port:
                  number: 8080
{{- end }}