{{- if .Values.oryx.storebuilder.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.oryx.storebuilder.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.oryx.storebuilder.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.gateway.type }}
data:
  "connect.properties": |
{{ .Values.oryx.storebuilder.settings.sinkProperties | indent 4 }}
{{- end }}
