{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.oryx.billing.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.oryx.billing.name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.oryx.billing.type }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /{{ .Release.Name }}-{{ .Values.oryx.billing.name }}/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.oryx.billing.name }}
                port:
                  number: 8080
{{- end }}
